// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { ISbStoryData } from 'storyblok';

export interface RichtextStoryblok {
	type: string;
	content?: RichtextStoryblok[];
	marks?: RichtextStoryblok[];
	attrs?: any;
	text?: string;
	[k: string]: any;
}

export interface HomeStoryblok {
	intro: RichtextStoryblok;
	component: 'home';
	_uid: string;
	[k: string]: any;
}

export interface AssetStoryblok {
	alt: string | null;
	copyright?: string | null;
	fieldtype: 'asset';
	id: number;
	filename: string | null;
	name: string;
	title: string | null;
	focus: string | null;
	meta_data?: {
		[k: string]: any;
	};
	source?: string | null;
	is_external_url?: boolean;
	is_private?: boolean;
	src?: string;
	updated_at?: string;
	width?: number | null;
	height?: number | null;
	aspect_ratio?: number | null;
	public_id?: string | null;
	content_type?: string;
	[k: string]: any;
}

export interface ImageStoryblok {
	image: AssetStoryblok;
	component: 'image';
	_uid: string;
	[k: string]: any;
}

export interface PageStoryblok {
	title: string;
	description?: string;
	banner?: AssetStoryblok;
	content: HomeStoryblok[];
	component: 'page';
	_uid: string;
	[k: string]: any;
}
