// This file was generated by the Storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { StoryblokAsset, StoryblokMultiasset, StoryblokMultilink, StoryblokRichTextDoc } from '../storyblok.d.ts';

export interface Banner {
	image: StoryblokAsset;
	link?: Exclude<StoryblokMultilink, { linktype?: 'email' } | { linktype?: 'asset' }>;
	linkText?: string;
	component: 'banner';
	_uid: string;
	_editable?: string | undefined;
}

export interface Config {
	contactName: string;
	contactEmail: string;
	contactPhone: string;
	navigation: (NavigationLink | NavigationGroup)[];
	component: 'config';
	_uid: string;
	_editable?: string | undefined;
}

export interface Directions {
	address: string;
	googleSearch: string;
	buttonText: string;
	component: 'directions';
	_uid: string;
	_editable?: string | undefined;
}

export interface EnsembleLink {
	ensemble: Exclude<StoryblokMultilink, { linktype?: 'email' } | { linktype?: 'asset' }>;
	component: 'ensembleLink';
	_uid: string;
	_editable?: string | undefined;
}

export interface EnsembleTeaser {
	title: StoryblokRichTextDoc;
	description: StoryblokRichTextDoc;
	link: Exclude<StoryblokMultilink, { linktype?: 'email' } | { linktype?: 'asset' }>;
	images: StoryblokMultiasset;
	component: 'ensembleTeaser';
	_uid: string;
	_editable?: string | undefined;
}

export interface EnsembleTeaserList {
	list: EnsembleTeaser[];
	component: 'ensembleTeaserList';
	_uid: string;
	_editable?: string | undefined;
}

export interface Event {
	start: string;
	end?: string;
	title: string;
	description?: StoryblokRichTextDoc;
	location?: string;
	ensembles?: EnsembleLink[];
	component: 'event';
	_uid: string;
	_editable?: string | undefined;
}

export interface EventList {
	events?: Event[];
	component: 'eventList';
	_uid: string;
	_editable?: string | undefined;
}

export interface Events {
	showMax: string;
	emptyText: string;
	buttonText: string;
	component: 'events';
	_uid: string;
	_editable?: string | undefined;
}

export interface Form {
	type: 'engage-home' | 'booking' | 'engage-ensemble';
	component: 'form';
	_uid: string;
	_editable?: string | undefined;
}

export interface Image {
	image: StoryblokAsset;
	component: 'image';
	_uid: string;
	_editable?: string | undefined;
}

export interface ImageSlider {
	images: StoryblokMultiasset;
	component: 'imageSlider';
	_uid: string;
	_editable?: string | undefined;
}

export interface NavigationGroup {
	title: StoryblokRichTextDoc;
	items: NavigationLink[];
	component: 'navigationGroup';
	_uid: string;
	_editable?: string | undefined;
}

export interface NavigationLink {
	link: Exclude<StoryblokMultilink, { linktype?: 'email' } | { linktype?: 'asset' }>;
	title: StoryblokRichTextDoc;
	component: 'navigationLink';
	_uid: string;
	_editable?: string | undefined;
}

export interface News {
	date: string;
	title: string;
	ensembles?: {
		[k: string]: unknown;
	}[];
	content: StoryblokRichTextDoc;
	component: 'news';
	_uid: string;
	_editable?: string | undefined;
}

export interface NewsList {
	component: 'newsList';
	_uid: string;
	_editable?: string | undefined;
}

export interface Page {
	title: string;
	description?: string;
	banner?: Banner[];
	content: StoryblokRichTextDoc;
	component: 'page';
	_uid: string;
	_editable?: string | undefined;
}

export interface TextAndLeader {
	name: string;
	image: StoryblokAsset;
	text: StoryblokRichTextDoc;
	component: 'textAndLeader';
	_uid: string;
	_editable?: string | undefined;
}

export type ContentType = Config | EventList | News | Page;
