// This file was generated by the storyblok CLI.
// DO NOT MODIFY THIS FILE BY HAND.
import type { StoryblokAsset, StoryblokMultiasset, StoryblokMultilink, StoryblokRichtext } from '../storyblok.d.ts';

export interface Banner {
	image: StoryblokAsset;
	link?: Exclude<StoryblokMultilink, { linktype?: 'email' } | { linktype?: 'asset' }>;
	linkText?: string;
	component: 'banner';
	_uid: string;
}

export interface Config {
	contactName: string;
	contactEmail: string;
	contactPhone: string;
	navigation: (NavigationLink | NavigationGroup)[];
	component: 'config';
	_uid: string;
}

export interface Directions {
	address: string;
	googleSearch: string;
	buttonText: string;
	component: 'directions';
	_uid: string;
}

export interface EnsembleTeaser {
	title: StoryblokRichtext;
	description: StoryblokRichtext;
	link: Exclude<StoryblokMultilink, { linktype?: 'email' } | { linktype?: 'asset' }>;
	images: StoryblokMultiasset;
	component: 'ensembleTeaser';
	_uid: string;
}

export interface EnsembleTeaserList {
	list: EnsembleTeaser[];
	component: 'ensembleTeaserList';
	_uid: string;
}

export interface Events {
	showMax: string;
	emptyText: string;
	buttonText: string;
	component: 'events';
	_uid: string;
}

export interface Form {
	type: 'engage-home' | 'booking' | 'engage-ensemble';
	component: 'form';
	_uid: string;
}

export interface Image {
	image: StoryblokAsset;
	component: 'image';
	_uid: string;
}

export interface ImageSlider {
	images: StoryblokMultiasset;
	component: 'imageSlider';
	_uid: string;
}

export interface NavigationGroup {
	title: StoryblokRichtext;
	items: NavigationLink[];
	component: 'navigationGroup';
	_uid: string;
}

export interface NavigationLink {
	link: Exclude<StoryblokMultilink, { linktype?: 'email' } | { linktype?: 'asset' }>;
	title: StoryblokRichtext;
	component: 'navigationLink';
	_uid: string;
}

export interface News {
	date: string;
	title: string;
	ensembles?: {
		[k: string]: unknown;
	}[];
	content: StoryblokRichtext;
	component: 'news';
	_uid: string;
}

export interface NewsList {
	component: 'newsList';
	_uid: string;
}

export interface Page {
	title: string;
	description?: string;
	banner?: Banner[];
	content: StoryblokRichtext;
	component: 'page';
	_uid: string;
}

export interface TextAndLeader {
	name: string;
	image: StoryblokAsset;
	text: StoryblokRichtext;
	component: 'textAndLeader';
	_uid: string;
}

export type ContentType = Config | News | Page;
